version: '3.7'
services:
    db:
        container_name: partiel_db
        image: 'mysql:8.0'
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    app:
        container_name: partiel_app
        build: docker/nginx
        depends_on:
            - db 
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
    composer:
        container_name: partiel_composer
        image: 'composer:1.7'
        command: install
        volumes:
            - './:/app'
    php-fpm:
        container_name: partiel_php-fpm
        build: docker/php
        volumes:
            - './:/usr/share/nginx/html'
    adminer:
        container_name: partiel_adminer
        image: 'adminer:4.7'
        ports:
            - '8081:8080'
